# Generated by Django 2.2.16 on 2020-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=50)),
                ('db_host', models.CharField(max_length=255, verbose_name='Database Host')),
                ('db_port', models.PositiveIntegerField(blank=True, verbose_name='Database Port')),
                ('db_user', models.CharField(max_length=50, verbose_name='Database User')),
                ('db_pass', models.CharField(max_length=255, verbose_name='Database Password')),
                ('db_name', models.CharField(max_length=50, verbose_name='Database Name')),
                ('db_table', models.CharField(blank=True, max_length=50, null=True, verbose_name='Database Table Name to Connect')),
                ('db_column', models.CharField(blank=True, max_length=30, null=True, verbose_name='Database Column to Compare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
