# Generated by Django 2.2.16 on 2020-09-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='db_column',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='db_table',
        ),
    ]
